general {
    lock_cmd = veila lock --wait-ready
    before_sleep_cmd = veila lock --wait-ready
    inhibit_sleep = 3
}

listener {
    timeout = 150                               # 2.5min.
    on-timeout = bash -c 'brightnessctl -s set $(( $(brightnessctl get) * 100 / $(brightnessctl m) > 21 ? $(brightnessctl get) - $(brightnessctl m) / 5 : $(brightnessctl m) / 100 ))'
    on-resume = brightnessctl -r
}

listener {
    timeout = 180                               # 3 min
    on-timeout = veila lock --wait-ready
}

listener {
    timeout = 210                               # 3.5 min
    on-timeout = systemctl suspend 
}

