theme = "window"
[background]
mode = "solid" 
[[visuals.backdrop]]
enabled = true
name = "auth_panel"
mode = "solid"
color = "#00000000"
blur_strength = 24
radius = 50
width = 540
height = 250
halign = "center"
valign = "center"
x = 0
y = 0
z = 0

