{ pkgs, ... }:
{
  environment.systemPackages = with pkgs; [
    zsh
    intel-gpu-tools
    catppuccin-sddm
    catppuccin-cursors
    vim
    neovim
    cava
    oh-my-zsh
    oh-my-posh
    wget
    foot
    fastfetch
    git
    unzip
    unrar
    btop
    brightnessctl
    brillo
    bluetui
    wiremix
    bat
    tree
    wev
    vlc
    prismlauncher
    gapless
    playerctl
    lshw
    xdg-desktop-portal-wlr
    kdePackages.polkit-kde-agent-1
    kdePackages.xdg-desktop-portal-kde
    kdePackages.dolphin
    kdePackages.ark
    kdePackages.dolphin-plugins
    kdePackages.qt6ct
    kdePackages.plasma-integration
    kdePackages.kservice
    kdePackages.kconfig
    kdePackages.kio
    kdePackages.kio-admin
    kdePackages.kde-cli-tools
    kdePackages.kguiaddons
    kdePackages.kio-extras
    kdePackages.gwenview
    hypridle
    hyprlock
    satty
    grim
    slurp
    rofi
    rofi-emoji
    impala
    clipse
    swaybg
  ];
}
